@echo off

setx POSTGRES_USERNAME "KENDI_KULLANICI_ADINI_YAZ"
setx POSTGRES_PASSWORD "KENDI_PAROLANI_YAZ"

setx JAVA_SECRETKEY "KENDI_JWT_SECRRET_ANAHTARINI_YAZ"
setx JAVA_ISSUER "KENDI_JWT_ISSUER_YAZ"

setx GIT_CONFIG_PROJECT "https://github.com/USERNAME/PROJE_ADI.git"
setx GIT_USERNAME "GITHUB_KULLANICI_ADINI_YAZ"
setx GIT_TOKEN_KEY "GITHUB_TOKEN_DEGERINI_YAZ"
---------------------------------------------------------------------------------------------------------
@echo off

setx POSTGRES_USERNAME "YOUR_POSTGRES_USERNAME_VALUE"
setx POSTGRES_PASSWORD "YOUR_POSTGRES_PASSWORD_VALUE"

setx JAVA_SECRETKEY "YOUR_JWT_SECRETKEY_VALUE"
setx JAVA_ISSUER "YOUR_JWT_ISSUER_VALUE"

setx GIT_CONFIG_PROJECT "https://github.com/YOUR_GITHUB_USERNAME_VALUE/YOUR_CONFIG_PROJECT_NAME.git"
setx GIT_USERNAME "YOUR_GITHUB_USERNAME_VALUE"
setx GIT_TOKEN_KEY "YOUR_GITHUB_TOKEN_KEY_VALUE"